sudo: required
services:
  - docker

before_install:
  - docker build -t trananhtu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trananhtu/docker-react npm run test -- --coverage